### PR TITLE
Updated Mumble.proto to support Channel Listeners (from mumble git)

### PR DESCRIPTION
**Pull request by jeffmikels**
Updated Mumble.proto to support Channel Listeners (from mumble git)

### CODE REVIEW

**Comment by EP-u-NW** [comment]
Thanks for your commits :)
It will take some time to review this changes (I think at least about a week, we got finals at uni atm...).

Can you give some more information on what you changed and explain why? 
I see your commit message says something about a Proxy Talk mode, can you explain this a bit?

Also, please make sure to add your name to the LICENSE file, so people know you have contributet to this project and to acknowledge the BSD2 style of this project ;)

**Comment by jeffmikels** [comment]
The latest (git) `Mumble.proto` allows for a client to "listen" to multiple channels if the server is 1.4+

To implement this feature in `dumble`, I needed to pull in the latest `Mumble.proto` and generated dart files, I needed to add the proper commands to the `Selfe` class in `user.dart`:

```dart
  void addListeningChannel({@required Channel channel}) => _client.writeMessage(
      new Proto.UserState()..listeningChannelAdd.add(channel.channelId));

  void removeListeningChannel({@required Channel channel}) =>
      _client.writeMessage(
          new Proto.UserState()..listeningChannelRemove.add(channel.channelId));
}
```

Additionally, Mumble server 1.4+ adds a new TalkMode that has a value of 3. Therefore in `audio.dart`

```dart
enum TalkMode { normal, whisperToChannel, whisperToUser, proxyListen }
```

I named the value `proxyListen` because 1.4+ refers to these additional listeners as "proxy" listeners.

Finally, I figured that the booleans under the User object should always have a value, so I'm proposing a change to make the getters return false when the actual value is null.

```dart
  bool get mute => _mute ?? false;
  bool get deaf => _deaf ?? false;
  bool get suppress => _suppress ?? false;
  bool get selfMute => _selfMute ?? false;
  bool get selfDeaf => _selfDeaf ?? false;
```

This is my personal preference, and if you don't like it, I will change it back.

The other commits were because I had my `dartfmt` set to use line lengths of 100 chars and noticed that after I made the commit. That certainly made the diffs harder to see.

**Comment by EP-u-NW** [comment]
So, as anounced, I finally had time to review the changes.

I just noticed 2 things:
1) The license file, I think it should be
```
Copyright 2020 Eric Prokop und Nils Wieler Hard- und Softwareentwicklung GbR
Copyright 2020 Jeffrey Mikels
```

2) You added a  `dev_dependency` on `opus_dart`
This should not be necessary since all test code is in the example folder, and `opus_dart` is referenced there.
I guess you added it to do some tests, but forgot to remove it 😅?

To again summarize your changes, in order to be sure I forgot something:
-  You corrected the file names of generated files. [Dart files should be named lowercase](https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores), so all the generated files from mumble.proto should have been lower case as well
- You added the `proxyListen` TalkMode
- You fixed a issue with `serializeVoiceTarget` where the `id` field in the proto messages was not set
- You changed the default bool values to `false` instead of null

About that last point: I don't see a reason why a default value of `false` could be a problem so, ok, let's change this.

I created a new develop branche in this repo, could you direct future pr's (I hope you'll do some 😁 ) there?
I think it might be good practice if we implement changes in the develop and keep the master consinstent with the pub hosted version.

Once you have revised the to points mentioned above I will accept the pr, increase the package version and push to pub!
Thanks again for your contribution 😊

P.S.: Could you provide a link to the proxy talk mode? I couldnt't find anything about it through google...
I'd assume it was designed as the user perspective equivalent to linked channles?

**Comment by EP-u-NW** [comment]
Channel listeners were added in 0.8.0 so this PR is obsolete.

**Pull request closed without merging**
